Add a rule checking for react components test coverage
ottofeller/dangerules pull request #6
Opened 2021-12-01 17:46 UTC by quesabe

2021-12-01 17:48 UTC, quesabe commented
Closes PLA-44.

2021-12-01 21:58 UTC, gvidon requested changes
@quesabe let's make sure that the rules does the following (according to [the slack discussion](https://ottofeller.slack.com/archives/GUAS246BU/p1638387797008200?thread_ts=1638380904.001700&cid=GUAS246BU)), check that:
* `__test__/[file name from rule config, e.g. index.tsx]` exists
* And has a `describe()` call with it.

2021-12-05 15:39 UTC, gvidon commented on src/react/__tests__/index.ts
> +    it('fails on a React component with a test file that has no component import', () => {
@quesabe 👍

2021-12-05 15:57 UTC, gvidon commented
Return early pla-44

2021-12-05 16:00 UTC, gvidon approved these changes

2021-12-05 16:00 UTC, merged